<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class PermissionGroupPermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        Schema::disableForeignKeyConstraints();

        DB::table('permission_group_permissions')->truncate();

        DB::table('permission_group_permissions')->insert([
            ['permission_group_id' => '1', 'permission_id' => '1'],
            ['permission_group_id' => '1', 'permission_id' => '2'],
            ['permission_group_id' => '1', 'permission_id' => '3'],
            ['permission_group_id' => '1', 'permission_id' => '4'],
            ['permission_group_id' => '1', 'permission_id' => '5'],
            ['permission_group_id' => '1', 'permission_id' => '6'],
            ['permission_group_id' => '1', 'permission_id' => '7'],
            ['permission_group_id' => '1', 'permission_id' => '8'],
            ['permission_group_id' => '1', 'permission_id' => '9'],
            ['permission_group_id' => '1', 'permission_id' => '10'],
            ['permission_group_id' => '1', 'permission_id' => '11'],
            ['permission_group_id' => '1', 'permission_id' => '12'],
            ['permission_group_id' => '1', 'permission_id' => '13'],
            ['permission_group_id' => '1', 'permission_id' => '14'],
            ['permission_group_id' => '1', 'permission_id' => '15'],
            ['permission_group_id' => '1', 'permission_id' => '16'],
            ['permission_group_id' => '1', 'permission_id' => '17'],
            ['permission_group_id' => '1', 'permission_id' => '18'],
            ['permission_group_id' => '1', 'permission_id' => '19'],
            ['permission_group_id' => '1', 'permission_id' => '20'],
            ['permission_group_id' => '1', 'permission_id' => '21'],
            ['permission_group_id' => '1', 'permission_id' => '22'],
            ['permission_group_id' => '1', 'permission_id' => '23'],
            ['permission_group_id' => '1', 'permission_id' => '24'],
            ['permission_group_id' => '1', 'permission_id' => '25'],
            ['permission_group_id' => '1', 'permission_id' => '26'],
            ['permission_group_id' => '1', 'permission_id' => '27'],
            ['permission_group_id' => '1', 'permission_id' => '28'],
            ['permission_group_id' => '1', 'permission_id' => '29'],
            ['permission_group_id' => '1', 'permission_id' => '30'],
            ['permission_group_id' => '1', 'permission_id' => '31'],
            ['permission_group_id' => '1', 'permission_id' => '32'],
            ['permission_group_id' => '1', 'permission_id' => '33'],
            ['permission_group_id' => '1', 'permission_id' => '34'],
            ['permission_group_id' => '1', 'permission_id' => '35'],
            ['permission_group_id' => '1', 'permission_id' => '36'],
            ['permission_group_id' => '1', 'permission_id' => '37'],
            ['permission_group_id' => '1', 'permission_id' => '38'],
            ['permission_group_id' => '1', 'permission_id' => '39'],
            ['permission_group_id' => '1', 'permission_id' => '40'],
            ['permission_group_id' => '1', 'permission_id' => '41'],
            ['permission_group_id' => '1', 'permission_id' => '42'],
            ['permission_group_id' => '1', 'permission_id' => '43'],
            ['permission_group_id' => '1', 'permission_id' => '44'],
            ['permission_group_id' => '1', 'permission_id' => '45'],
            ['permission_group_id' => '1', 'permission_id' => '46'],
            ['permission_group_id' => '1', 'permission_id' => '47'],
            ['permission_group_id' => '1', 'permission_id' => '48'],
            ['permission_group_id' => '1', 'permission_id' => '49'],
            ['permission_group_id' => '1', 'permission_id' => '50'],
            ['permission_group_id' => '1', 'permission_id' => '51'],
            ['permission_group_id' => '1', 'permission_id' => '52'],
            ['permission_group_id' => '1', 'permission_id' => '53'],
            ['permission_group_id' => '1', 'permission_id' => '54'],
            ['permission_group_id' => '1', 'permission_id' => '55'],
            ['permission_group_id' => '1', 'permission_id' => '56'],
            ['permission_group_id' => '1', 'permission_id' => '57'],
            ['permission_group_id' => '1', 'permission_id' => '58'],
            ['permission_group_id' => '1', 'permission_id' => '59'],
            ['permission_group_id' => '1', 'permission_id' => '60'],
            ['permission_group_id' => '1', 'permission_id' => '61'],
            ['permission_group_id' => '1', 'permission_id' => '62'],
            ['permission_group_id' => '1', 'permission_id' => '63'],
            ['permission_group_id' => '1', 'permission_id' => '64'],
            ['permission_group_id' => '1', 'permission_id' => '65'],
            ['permission_group_id' => '1', 'permission_id' => '66'],
            ['permission_group_id' => '1', 'permission_id' => '67'],
            ['permission_group_id' => '1', 'permission_id' => '68'],
            ['permission_group_id' => '1', 'permission_id' => '69'],
            ['permission_group_id' => '1', 'permission_id' => '70'],
            ['permission_group_id' => '1', 'permission_id' => '71'],
            ['permission_group_id' => '1', 'permission_id' => '72'],
            ['permission_group_id' => '1', 'permission_id' => '73'],
            ['permission_group_id' => '1', 'permission_id' => '74'],
            ['permission_group_id' => '1', 'permission_id' => '75'],
            ['permission_group_id' => '1', 'permission_id' => '76'],
            ['permission_group_id' => '1', 'permission_id' => '77'],
            ['permission_group_id' => '1', 'permission_id' => '78'],
            ['permission_group_id' => '1', 'permission_id' => '79'],
            ['permission_group_id' => '1', 'permission_id' => '80'],
            ['permission_group_id' => '1', 'permission_id' => '81'],
            ['permission_group_id' => '1', 'permission_id' => '82'],
            ['permission_group_id' => '1', 'permission_id' => '83'],
            ['permission_group_id' => '1', 'permission_id' => '84'],
            ['permission_group_id' => '1', 'permission_id' => '85'],
            ['permission_group_id' => '1', 'permission_id' => '86'],
            ['permission_group_id' => '1', 'permission_id' => '87'],
            ['permission_group_id' => '1', 'permission_id' => '88'],
            ['permission_group_id' => '1', 'permission_id' => '89'],
            ['permission_group_id' => '1', 'permission_id' => '90'],
            ['permission_group_id' => '1', 'permission_id' => '91'],
            ['permission_group_id' => '1', 'permission_id' => '92'],
            ['permission_group_id' => '1', 'permission_id' => '93'],
            ['permission_group_id' => '1', 'permission_id' => '94'],
            ['permission_group_id' => '1', 'permission_id' => '95'],
            ['permission_group_id' => '1', 'permission_id' => '96'],
            ['permission_group_id' => '1', 'permission_id' => '97'],
            ['permission_group_id' => '1', 'permission_id' => '98'],
            ['permission_group_id' => '1', 'permission_id' => '99'],
            ['permission_group_id' => '1', 'permission_id' => '100'],
            ['permission_group_id' => '1', 'permission_id' => '101'],
            ['permission_group_id' => '1', 'permission_id' => '102'],
            ['permission_group_id' => '1', 'permission_id' => '103'],
            ['permission_group_id' => '1', 'permission_id' => '104'],
            ['permission_group_id' => '1', 'permission_id' => '105'],
            ['permission_group_id' => '1', 'permission_id' => '106'],
            ['permission_group_id' => '1', 'permission_id' => '107'],
            ['permission_group_id' => '1', 'permission_id' => '108'],
            ['permission_group_id' => '1', 'permission_id' => '109'],
            ['permission_group_id' => '1', 'permission_id' => '110'],
            ['permission_group_id' => '1', 'permission_id' => '111'],
            ['permission_group_id' => '1', 'permission_id' => '112'],
            ['permission_group_id' => '1', 'permission_id' => '113'],
            ['permission_group_id' => '1', 'permission_id' => '114'],
            ['permission_group_id' => '1', 'permission_id' => '115'],
            ['permission_group_id' => '1', 'permission_id' => '116'],
            ['permission_group_id' => '1', 'permission_id' => '117'],
            ['permission_group_id' => '1', 'permission_id' => '118'],
            ['permission_group_id' => '1', 'permission_id' => '119'],
            ['permission_group_id' => '1', 'permission_id' => '120'],
            ['permission_group_id' => '1', 'permission_id' => '121'],
            ['permission_group_id' => '1', 'permission_id' => '122'],
            ['permission_group_id' => '1', 'permission_id' => '123'],
            ['permission_group_id' => '1', 'permission_id' => '124'],
            ['permission_group_id' => '1', 'permission_id' => '125'],
            ['permission_group_id' => '1', 'permission_id' => '126'],
            ['permission_group_id' => '1', 'permission_id' => '127'],
            ['permission_group_id' => '1', 'permission_id' => '128'],
            ['permission_group_id' => '1', 'permission_id' => '129'],
            ['permission_group_id' => '1', 'permission_id' => '130'],
            ['permission_group_id' => '1', 'permission_id' => '131'],
            ['permission_group_id' => '1', 'permission_id' => '132'],
            ['permission_group_id' => '1', 'permission_id' => '133'],
            ['permission_group_id' => '1', 'permission_id' => '134'],
            ['permission_group_id' => '1', 'permission_id' => '135'],
            ['permission_group_id' => '1', 'permission_id' => '136'],
            ['permission_group_id' => '1', 'permission_id' => '137'],
            ['permission_group_id' => '1', 'permission_id' => '138'],
            ['permission_group_id' => '1', 'permission_id' => '139'],
            ['permission_group_id' => '1', 'permission_id' => '140'],
            ['permission_group_id' => '1', 'permission_id' => '141'],
            ['permission_group_id' => '1', 'permission_id' => '142'],
            ['permission_group_id' => '1', 'permission_id' => '143'],
            ['permission_group_id' => '1', 'permission_id' => '144'],
            ['permission_group_id' => '1', 'permission_id' => '145'],
            ['permission_group_id' => '1', 'permission_id' => '146'],
            ['permission_group_id' => '1', 'permission_id' => '147'],
            ['permission_group_id' => '1', 'permission_id' => '148'],
            ['permission_group_id' => '1', 'permission_id' => '149'],
            ['permission_group_id' => '1', 'permission_id' => '150'],
            ['permission_group_id' => '1', 'permission_id' => '151'],
            ['permission_group_id' => '1', 'permission_id' => '152'],
            ['permission_group_id' => '1', 'permission_id' => '153'],
            ['permission_group_id' => '1', 'permission_id' => '154'],
            ['permission_group_id' => '1', 'permission_id' => '155'],
            ['permission_group_id' => '1', 'permission_id' => '156'],
            ['permission_group_id' => '1', 'permission_id' => '157'],
            ['permission_group_id' => '1', 'permission_id' => '158'],
            ['permission_group_id' => '1', 'permission_id' => '159'],
            ['permission_group_id' => '1', 'permission_id' => '160'],
            ['permission_group_id' => '1', 'permission_id' => '161'],
            ['permission_group_id' => '1', 'permission_id' => '162'],
            ['permission_group_id' => '1', 'permission_id' => '163'],
            ['permission_group_id' => '1', 'permission_id' => '164'],
            ['permission_group_id' => '1', 'permission_id' => '165'],
            ['permission_group_id' => '1', 'permission_id' => '166'],
            ['permission_group_id' => '1', 'permission_id' => '167'],
            ['permission_group_id' => '1', 'permission_id' => '168'],
            ['permission_group_id' => '1', 'permission_id' => '169'],
            ['permission_group_id' => '1', 'permission_id' => '170'],
            ['permission_group_id' => '1', 'permission_id' => '171'],
            ['permission_group_id' => '1', 'permission_id' => '172'],
            ['permission_group_id' => '1', 'permission_id' => '173'],
            ['permission_group_id' => '1', 'permission_id' => '174'],
            ['permission_group_id' => '1', 'permission_id' => '175'],
            ['permission_group_id' => '1', 'permission_id' => '176'],
            ['permission_group_id' => '1', 'permission_id' => '177'],
            ['permission_group_id' => '1', 'permission_id' => '178'],
            ['permission_group_id' => '1', 'permission_id' => '179'],
            ['permission_group_id' => '1', 'permission_id' => '180'],
            ['permission_group_id' => '1', 'permission_id' => '181'],
            ['permission_group_id' => '1', 'permission_id' => '182'],
            ['permission_group_id' => '1', 'permission_id' => '183'],
            ['permission_group_id' => '1', 'permission_id' => '184'],
            ['permission_group_id' => '1', 'permission_id' => '185'],
            ['permission_group_id' => '1', 'permission_id' => '186'],
            ['permission_group_id' => '1', 'permission_id' => '187'],
            ['permission_group_id' => '1', 'permission_id' => '188'],
            ['permission_group_id' => '1', 'permission_id' => '189'],
            ['permission_group_id' => '1', 'permission_id' => '190'],
            ['permission_group_id' => '1', 'permission_id' => '191'],
            ['permission_group_id' => '1', 'permission_id' => '192'],
            ['permission_group_id' => '1', 'permission_id' => '193'],
            ['permission_group_id' => '1', 'permission_id' => '194'],
            ['permission_group_id' => '1', 'permission_id' => '195'],
            ['permission_group_id' => '1', 'permission_id' => '196'],
            ['permission_group_id' => '1', 'permission_id' => '197'],
            ['permission_group_id' => '1', 'permission_id' => '198'],
            ['permission_group_id' => '1', 'permission_id' => '199'],
            ['permission_group_id' => '1', 'permission_id' => '200'],
            ['permission_group_id' => '1', 'permission_id' => '201'],
            ['permission_group_id' => '1', 'permission_id' => '202'],
            ['permission_group_id' => '1', 'permission_id' => '203'],
            ['permission_group_id' => '1', 'permission_id' => '204'],
            ['permission_group_id' => '1', 'permission_id' => '205'],
            ['permission_group_id' => '1', 'permission_id' => '206'],
            ['permission_group_id' => '1', 'permission_id' => '207'],
            ['permission_group_id' => '1', 'permission_id' => '208'],
            ['permission_group_id' => '1', 'permission_id' => '209'],
            ['permission_group_id' => '1', 'permission_id' => '210'],
            ['permission_group_id' => '1', 'permission_id' => '211'],
            ['permission_group_id' => '1', 'permission_id' => '212'],
            ['permission_group_id' => '1', 'permission_id' => '213'],
            ['permission_group_id' => '1', 'permission_id' => '214'],
            ['permission_group_id' => '1', 'permission_id' => '215'],
            ['permission_group_id' => '1', 'permission_id' => '216'],
            ['permission_group_id' => '1', 'permission_id' => '217'],
            ['permission_group_id' => '1', 'permission_id' => '218'],
            ['permission_group_id' => '1', 'permission_id' => '219'],
            ['permission_group_id' => '1', 'permission_id' => '220'],
            ['permission_group_id' => '1', 'permission_id' => '221'],
            ['permission_group_id' => '1', 'permission_id' => '222'],
            ['permission_group_id' => '1', 'permission_id' => '223'],
            ['permission_group_id' => '1', 'permission_id' => '224'],
            ['permission_group_id' => '1', 'permission_id' => '238'],
            ['permission_group_id' => '1', 'permission_id' => '239']
        ]);

        Schema::enableForeignKeyConstraints();


    }
}
