{{ if (.Values.enableEngress) }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Chart.Name }}-ingress"
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  tls:
    - hosts:
        - "{{ .Values.VAR.APP_URL }}"
      secretName: "{{ .Chart.Name }}-secret"
  rules:
    - host: "{{ .Values.VAR.APP_URL }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  name: http
{{end}}