<?php
/**
 * DivisionApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * DivisionApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DivisionApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1DivisionsDivisionIdGet
     *
     * get one
     *
     * @param  int $division_id division_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1DivisionsDivisionIdGet($division_id)
    {
        $this->apiV1DivisionsDivisionIdGetWithHttpInfo($division_id);
    }

    /**
     * Operation apiV1DivisionsDivisionIdGetWithHttpInfo
     *
     * get one
     *
     * @param  int $division_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DivisionsDivisionIdGetWithHttpInfo($division_id)
    {
        $request = $this->apiV1DivisionsDivisionIdGetRequest($division_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1DivisionsDivisionIdGetAsync
     *
     * get one
     *
     * @param  int $division_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DivisionsDivisionIdGetAsync($division_id)
    {
        return $this->apiV1DivisionsDivisionIdGetAsyncWithHttpInfo($division_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DivisionsDivisionIdGetAsyncWithHttpInfo
     *
     * get one
     *
     * @param  int $division_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DivisionsDivisionIdGetAsyncWithHttpInfo($division_id)
    {
        $returnType = '';
        $request = $this->apiV1DivisionsDivisionIdGetRequest($division_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DivisionsDivisionIdGet'
     *
     * @param  int $division_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1DivisionsDivisionIdGetRequest($division_id)
    {
        // verify the required parameter 'division_id' is set
        if ($division_id === null || (is_array($division_id) && count($division_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $division_id when calling apiV1DivisionsDivisionIdGet'
            );
        }

        $resourcePath = '/api/v1/divisions/{divisionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($division_id !== null) {
            $resourcePath = str_replace(
                '{' . 'divisionId' . '}',
                ObjectSerializer::toPathValue($division_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1DivisionsGet
     *
     * get list
     *
     * @param  int $page page (optional)
     * @param  string $order order (optional)
     * @param  string $title_en title_en (optional)
     * @param  string $title_bn title_bn (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1DivisionsGet($page = null, $order = null, $title_en = null, $title_bn = null)
    {
        $this->apiV1DivisionsGetWithHttpInfo($page, $order, $title_en, $title_bn);
    }

    /**
     * Operation apiV1DivisionsGetWithHttpInfo
     *
     * get list
     *
     * @param  int $page (optional)
     * @param  string $order (optional)
     * @param  string $title_en (optional)
     * @param  string $title_bn (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1DivisionsGetWithHttpInfo($page = null, $order = null, $title_en = null, $title_bn = null)
    {
        $request = $this->apiV1DivisionsGetRequest($page, $order, $title_en, $title_bn);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1DivisionsGetAsync
     *
     * get list
     *
     * @param  int $page (optional)
     * @param  string $order (optional)
     * @param  string $title_en (optional)
     * @param  string $title_bn (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DivisionsGetAsync($page = null, $order = null, $title_en = null, $title_bn = null)
    {
        return $this->apiV1DivisionsGetAsyncWithHttpInfo($page, $order, $title_en, $title_bn)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1DivisionsGetAsyncWithHttpInfo
     *
     * get list
     *
     * @param  int $page (optional)
     * @param  string $order (optional)
     * @param  string $title_en (optional)
     * @param  string $title_bn (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1DivisionsGetAsyncWithHttpInfo($page = null, $order = null, $title_en = null, $title_bn = null)
    {
        $returnType = '';
        $request = $this->apiV1DivisionsGetRequest($page, $order, $title_en, $title_bn);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1DivisionsGet'
     *
     * @param  int $page (optional)
     * @param  string $order (optional)
     * @param  string $title_en (optional)
     * @param  string $title_bn (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1DivisionsGetRequest($page = null, $order = null, $title_en = null, $title_bn = null)
    {

        $resourcePath = '/api/v1/divisions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($page !== null) {
            if('form' === 'form' && is_array($page)) {
                foreach($page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page'] = $page;
            }
        }
        // query params
        if ($order !== null) {
            if('form' === 'form' && is_array($order)) {
                foreach($order as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['order'] = $order;
            }
        }
        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation destroy
     *
     * delete
     *
     * @param  int $division_id division_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function destroy($division_id)
    {
        $this->destroyWithHttpInfo($division_id);
    }

    /**
     * Operation destroyWithHttpInfo
     *
     * delete
     *
     * @param  int $division_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function destroyWithHttpInfo($division_id)
    {
        $request = $this->destroyRequest($division_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation destroyAsync
     *
     * delete
     *
     * @param  int $division_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function destroyAsync($division_id)
    {
        return $this->destroyAsyncWithHttpInfo($division_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation destroyAsyncWithHttpInfo
     *
     * delete
     *
     * @param  int $division_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function destroyAsyncWithHttpInfo($division_id)
    {
        $returnType = '';
        $request = $this->destroyRequest($division_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'destroy'
     *
     * @param  int $division_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function destroyRequest($division_id)
    {
        // verify the required parameter 'division_id' is set
        if ($division_id === null || (is_array($division_id) && count($division_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $division_id when calling destroy'
            );
        }

        $resourcePath = '/api/v1/divisions/{divisionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($division_id !== null) {
            $resourcePath = str_replace(
                '{' . 'divisionId' . '}',
                ObjectSerializer::toPathValue($division_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation store
     *
     * store
     *
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $bbs_code bbs_code (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function store($title_en, $title_bn, $bbs_code = null)
    {
        $this->storeWithHttpInfo($title_en, $title_bn, $bbs_code);
    }

    /**
     * Operation storeWithHttpInfo
     *
     * store
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $bbs_code (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function storeWithHttpInfo($title_en, $title_bn, $bbs_code = null)
    {
        $request = $this->storeRequest($title_en, $title_bn, $bbs_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation storeAsync
     *
     * store
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $bbs_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeAsync($title_en, $title_bn, $bbs_code = null)
    {
        return $this->storeAsyncWithHttpInfo($title_en, $title_bn, $bbs_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storeAsyncWithHttpInfo
     *
     * store
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $bbs_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storeAsyncWithHttpInfo($title_en, $title_bn, $bbs_code = null)
    {
        $returnType = '';
        $request = $this->storeRequest($title_en, $title_bn, $bbs_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'store'
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $bbs_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function storeRequest($title_en, $title_bn, $bbs_code = null)
    {
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling store'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling store'
            );
        }
        if ($bbs_code !== null && strlen($bbs_code) > 4) {
            throw new \InvalidArgumentException('invalid length for "$bbs_code" when calling DivisionApi.store, must be smaller than or equal to 4.');
        }


        $resourcePath = '/api/v1/divisions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($bbs_code !== null) {
            if('form' === 'form' && is_array($bbs_code)) {
                foreach($bbs_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['bbs_code'] = $bbs_code;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation update
     *
     * update
     *
     * @param  int $division_id division_id (required)
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  float $bbs_code bbs_code (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function update($division_id, $title_en, $title_bn, $bbs_code = null)
    {
        $this->updateWithHttpInfo($division_id, $title_en, $title_bn, $bbs_code);
    }

    /**
     * Operation updateWithHttpInfo
     *
     * update
     *
     * @param  int $division_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  float $bbs_code (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateWithHttpInfo($division_id, $title_en, $title_bn, $bbs_code = null)
    {
        $request = $this->updateRequest($division_id, $title_en, $title_bn, $bbs_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation updateAsync
     *
     * update
     *
     * @param  int $division_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  float $bbs_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAsync($division_id, $title_en, $title_bn, $bbs_code = null)
    {
        return $this->updateAsyncWithHttpInfo($division_id, $title_en, $title_bn, $bbs_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAsyncWithHttpInfo
     *
     * update
     *
     * @param  int $division_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  float $bbs_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAsyncWithHttpInfo($division_id, $title_en, $title_bn, $bbs_code = null)
    {
        $returnType = '';
        $request = $this->updateRequest($division_id, $title_en, $title_bn, $bbs_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'update'
     *
     * @param  int $division_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  float $bbs_code (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateRequest($division_id, $title_en, $title_bn, $bbs_code = null)
    {
        // verify the required parameter 'division_id' is set
        if ($division_id === null || (is_array($division_id) && count($division_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $division_id when calling update'
            );
        }
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling update'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling update'
            );
        }
        if ($bbs_code !== null && strlen($bbs_code) > 4) {
            throw new \InvalidArgumentException('invalid length for "$bbs_code" when calling DivisionApi.update, must be smaller than or equal to 4.');
        }


        $resourcePath = '/api/v1/divisions/{divisionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($bbs_code !== null) {
            if('form' === 'form' && is_array($bbs_code)) {
                foreach($bbs_code as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['bbs_code'] = $bbs_code;
            }
        }


        // path params
        if ($division_id !== null) {
            $resourcePath = str_replace(
                '{' . 'divisionId' . '}',
                ObjectSerializer::toPathValue($division_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
