<?php
/**
 * PermissionSubGroupServiceApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * PermissionSubGroupServiceApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PermissionSubGroupServiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1PermissionSubGroupsGet
     *
     * get list
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionSubGroupsGet()
    {
        $this->apiV1PermissionSubGroupsGetWithHttpInfo();
    }

    /**
     * Operation apiV1PermissionSubGroupsGetWithHttpInfo
     *
     * get list
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionSubGroupsGetWithHttpInfo()
    {
        $request = $this->apiV1PermissionSubGroupsGetRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionSubGroupsGetAsync
     *
     * get list
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsGetAsync()
    {
        return $this->apiV1PermissionSubGroupsGetAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionSubGroupsGetAsyncWithHttpInfo
     *
     * get list
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsGetAsyncWithHttpInfo()
    {
        $returnType = '';
        $request = $this->apiV1PermissionSubGroupsGetRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionSubGroupsGet'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionSubGroupsGetRequest()
    {

        $resourcePath = '/api/v1/permission-sub-groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPost
     *
     * assign-permission
     *
     * @param  int $permission_sub_group_id permission_sub_group_id (required)
     * @param  int $permissions_0 permissions_0 (optional)
     * @param  int $permissions_1 permissions_1 (optional)
     * @param  int $permissions_2 permissions_2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPost($permission_sub_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $this->apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostWithHttpInfo($permission_sub_group_id, $permissions_0, $permissions_1, $permissions_2);
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostWithHttpInfo
     *
     * assign-permission
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostWithHttpInfo($permission_sub_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $request = $this->apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostRequest($permission_sub_group_id, $permissions_0, $permissions_1, $permissions_2);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostAsync
     *
     * assign-permission
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostAsync($permission_sub_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        return $this->apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostAsyncWithHttpInfo($permission_sub_group_id, $permissions_0, $permissions_1, $permissions_2)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostAsyncWithHttpInfo
     *
     * assign-permission
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostAsyncWithHttpInfo($permission_sub_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $returnType = '';
        $request = $this->apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostRequest($permission_sub_group_id, $permissions_0, $permissions_1, $permissions_2);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPost'
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPostRequest($permission_sub_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        // verify the required parameter 'permission_sub_group_id' is set
        if ($permission_sub_group_id === null || (is_array($permission_sub_group_id) && count($permission_sub_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_sub_group_id when calling apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPost'
            );
        }

        $resourcePath = '/api/v1/permission-sub-groups/{permissionSubGroupId}/assign-permissions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($permissions_0 !== null) {
            if('form' === 'form' && is_array($permissions_0)) {
                foreach($permissions_0 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[0]'] = $permissions_0;
            }
        }
        // query params
        if ($permissions_1 !== null) {
            if('form' === 'form' && is_array($permissions_1)) {
                foreach($permissions_1 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[1]'] = $permissions_1;
            }
        }
        // query params
        if ($permissions_2 !== null) {
            if('form' === 'form' && is_array($permissions_2)) {
                foreach($permissions_2 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[2]'] = $permissions_2;
            }
        }


        // path params
        if ($permission_sub_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionSubGroupId' . '}',
                ObjectSerializer::toPathValue($permission_sub_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdDelete
     *
     * delete
     *
     * @param  int $permission_sub_group_id permission_sub_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdDelete($permission_sub_group_id)
    {
        $this->apiV1PermissionSubGroupsPermissionSubGroupIdDeleteWithHttpInfo($permission_sub_group_id);
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdDeleteWithHttpInfo
     *
     * delete
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdDeleteWithHttpInfo($permission_sub_group_id)
    {
        $request = $this->apiV1PermissionSubGroupsPermissionSubGroupIdDeleteRequest($permission_sub_group_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdDeleteAsync
     *
     * delete
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdDeleteAsync($permission_sub_group_id)
    {
        return $this->apiV1PermissionSubGroupsPermissionSubGroupIdDeleteAsyncWithHttpInfo($permission_sub_group_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdDeleteAsyncWithHttpInfo
     *
     * delete
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdDeleteAsyncWithHttpInfo($permission_sub_group_id)
    {
        $returnType = '';
        $request = $this->apiV1PermissionSubGroupsPermissionSubGroupIdDeleteRequest($permission_sub_group_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionSubGroupsPermissionSubGroupIdDelete'
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionSubGroupsPermissionSubGroupIdDeleteRequest($permission_sub_group_id)
    {
        // verify the required parameter 'permission_sub_group_id' is set
        if ($permission_sub_group_id === null || (is_array($permission_sub_group_id) && count($permission_sub_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_sub_group_id when calling apiV1PermissionSubGroupsPermissionSubGroupIdDelete'
            );
        }

        $resourcePath = '/api/v1/permission-sub-groups/{permissionSubGroupId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($permission_sub_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionSubGroupId' . '}',
                ObjectSerializer::toPathValue($permission_sub_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdGet
     *
     * get one
     *
     * @param  int $permission_sub_group_id permission_sub_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdGet($permission_sub_group_id)
    {
        $this->apiV1PermissionSubGroupsPermissionSubGroupIdGetWithHttpInfo($permission_sub_group_id);
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdGetWithHttpInfo
     *
     * get one
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdGetWithHttpInfo($permission_sub_group_id)
    {
        $request = $this->apiV1PermissionSubGroupsPermissionSubGroupIdGetRequest($permission_sub_group_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdGetAsync
     *
     * get one
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdGetAsync($permission_sub_group_id)
    {
        return $this->apiV1PermissionSubGroupsPermissionSubGroupIdGetAsyncWithHttpInfo($permission_sub_group_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionSubGroupsPermissionSubGroupIdGetAsyncWithHttpInfo
     *
     * get one
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPermissionSubGroupIdGetAsyncWithHttpInfo($permission_sub_group_id)
    {
        $returnType = '';
        $request = $this->apiV1PermissionSubGroupsPermissionSubGroupIdGetRequest($permission_sub_group_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionSubGroupsPermissionSubGroupIdGet'
     *
     * @param  int $permission_sub_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionSubGroupsPermissionSubGroupIdGetRequest($permission_sub_group_id)
    {
        // verify the required parameter 'permission_sub_group_id' is set
        if ($permission_sub_group_id === null || (is_array($permission_sub_group_id) && count($permission_sub_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_sub_group_id when calling apiV1PermissionSubGroupsPermissionSubGroupIdGet'
            );
        }

        $resourcePath = '/api/v1/permission-sub-groups/{permissionSubGroupId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($permission_sub_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionSubGroupId' . '}',
                ObjectSerializer::toPathValue($permission_sub_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionSubGroupsPost
     *
     * create
     *
     * @param  int $permission_group_id permission_group_id (required)
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $key key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionSubGroupsPost($permission_group_id, $title_en, $title_bn, $key)
    {
        $this->apiV1PermissionSubGroupsPostWithHttpInfo($permission_group_id, $title_en, $title_bn, $key);
    }

    /**
     * Operation apiV1PermissionSubGroupsPostWithHttpInfo
     *
     * create
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionSubGroupsPostWithHttpInfo($permission_group_id, $title_en, $title_bn, $key)
    {
        $request = $this->apiV1PermissionSubGroupsPostRequest($permission_group_id, $title_en, $title_bn, $key);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionSubGroupsPostAsync
     *
     * create
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPostAsync($permission_group_id, $title_en, $title_bn, $key)
    {
        return $this->apiV1PermissionSubGroupsPostAsyncWithHttpInfo($permission_group_id, $title_en, $title_bn, $key)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionSubGroupsPostAsyncWithHttpInfo
     *
     * create
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionSubGroupsPostAsyncWithHttpInfo($permission_group_id, $title_en, $title_bn, $key)
    {
        $returnType = '';
        $request = $this->apiV1PermissionSubGroupsPostRequest($permission_group_id, $title_en, $title_bn, $key);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionSubGroupsPost'
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionSubGroupsPostRequest($permission_group_id, $title_en, $title_bn, $key)
    {
        // verify the required parameter 'permission_group_id' is set
        if ($permission_group_id === null || (is_array($permission_group_id) && count($permission_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_group_id when calling apiV1PermissionSubGroupsPost'
            );
        }
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling apiV1PermissionSubGroupsPost'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling apiV1PermissionSubGroupsPost'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling apiV1PermissionSubGroupsPost'
            );
        }

        $resourcePath = '/api/v1/permission-sub-groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($permission_group_id !== null) {
            if('form' === 'form' && is_array($permission_group_id)) {
                foreach($permission_group_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permission_group_id'] = $permission_group_id;
            }
        }
        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($key !== null) {
            if('form' === 'form' && is_array($key)) {
                foreach($key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key'] = $key;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation update4
     *
     * update
     *
     * @param  int $permission_sub_group_id permission_sub_group_id (required)
     * @param  int $permission_group_id permission_group_id (required)
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $key key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function update4($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key)
    {
        $this->update4WithHttpInfo($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key);
    }

    /**
     * Operation update4WithHttpInfo
     *
     * update
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function update4WithHttpInfo($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key)
    {
        $request = $this->update4Request($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation update4Async
     *
     * update
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function update4Async($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key)
    {
        return $this->update4AsyncWithHttpInfo($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation update4AsyncWithHttpInfo
     *
     * update
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function update4AsyncWithHttpInfo($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key)
    {
        $returnType = '';
        $request = $this->update4Request($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'update4'
     *
     * @param  int $permission_sub_group_id (required)
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function update4Request($permission_sub_group_id, $permission_group_id, $title_en, $title_bn, $key)
    {
        // verify the required parameter 'permission_sub_group_id' is set
        if ($permission_sub_group_id === null || (is_array($permission_sub_group_id) && count($permission_sub_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_sub_group_id when calling update4'
            );
        }
        // verify the required parameter 'permission_group_id' is set
        if ($permission_group_id === null || (is_array($permission_group_id) && count($permission_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_group_id when calling update4'
            );
        }
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling update4'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling update4'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling update4'
            );
        }

        $resourcePath = '/api/v1/permission-sub-groups/{permissionSubGroupId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($permission_group_id !== null) {
            if('form' === 'form' && is_array($permission_group_id)) {
                foreach($permission_group_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permission_group_id'] = $permission_group_id;
            }
        }
        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($key !== null) {
            if('form' === 'form' && is_array($key)) {
                foreach($key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key'] = $key;
            }
        }


        // path params
        if ($permission_sub_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionSubGroupId' . '}',
                ObjectSerializer::toPathValue($permission_sub_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
