<?php
/**
 * PermissionGroupServiceApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * PermissionGroupServiceApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PermissionGroupServiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPost
     *
     * assign-permission
     *
     * @param  int $permission_group_id permission_group_id (required)
     * @param  int $permissions_0 permissions_0 (optional)
     * @param  int $permissions_1 permissions_1 (optional)
     * @param  int $permissions_2 permissions_2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPost($permission_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $this->apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostWithHttpInfo($permission_group_id, $permissions_0, $permissions_1, $permissions_2);
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostWithHttpInfo
     *
     * assign-permission
     *
     * @param  int $permission_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostWithHttpInfo($permission_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $request = $this->apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostRequest($permission_group_id, $permissions_0, $permissions_1, $permissions_2);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostAsync
     *
     * assign-permission
     *
     * @param  int $permission_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostAsync($permission_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        return $this->apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostAsyncWithHttpInfo($permission_group_id, $permissions_0, $permissions_1, $permissions_2)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostAsyncWithHttpInfo
     *
     * assign-permission
     *
     * @param  int $permission_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostAsyncWithHttpInfo($permission_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $returnType = '';
        $request = $this->apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostRequest($permission_group_id, $permissions_0, $permissions_1, $permissions_2);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPost'
     *
     * @param  int $permission_group_id (required)
     * @param  int $permissions_0 (optional)
     * @param  int $permissions_1 (optional)
     * @param  int $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPostRequest($permission_group_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        // verify the required parameter 'permission_group_id' is set
        if ($permission_group_id === null || (is_array($permission_group_id) && count($permission_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_group_id when calling apiV1PermissionGroupsPermissionGroupIdAssignPermissionsPost'
            );
        }

        $resourcePath = '/api/v1/permission-groups/{permissionGroupId}/assign-permissions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($permissions_0 !== null) {
            if('form' === 'form' && is_array($permissions_0)) {
                foreach($permissions_0 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[0]'] = $permissions_0;
            }
        }
        // query params
        if ($permissions_1 !== null) {
            if('form' === 'form' && is_array($permissions_1)) {
                foreach($permissions_1 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[1]'] = $permissions_1;
            }
        }
        // query params
        if ($permissions_2 !== null) {
            if('form' === 'form' && is_array($permissions_2)) {
                foreach($permissions_2 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[2]'] = $permissions_2;
            }
        }


        // path params
        if ($permission_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionGroupId' . '}',
                ObjectSerializer::toPathValue($permission_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdDelete
     *
     * delete
     *
     * @param  int $permission_group_id permission_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionGroupsPermissionGroupIdDelete($permission_group_id)
    {
        $this->apiV1PermissionGroupsPermissionGroupIdDeleteWithHttpInfo($permission_group_id);
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdDeleteWithHttpInfo
     *
     * delete
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionGroupsPermissionGroupIdDeleteWithHttpInfo($permission_group_id)
    {
        $request = $this->apiV1PermissionGroupsPermissionGroupIdDeleteRequest($permission_group_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdDeleteAsync
     *
     * delete
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdDeleteAsync($permission_group_id)
    {
        return $this->apiV1PermissionGroupsPermissionGroupIdDeleteAsyncWithHttpInfo($permission_group_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdDeleteAsyncWithHttpInfo
     *
     * delete
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdDeleteAsyncWithHttpInfo($permission_group_id)
    {
        $returnType = '';
        $request = $this->apiV1PermissionGroupsPermissionGroupIdDeleteRequest($permission_group_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionGroupsPermissionGroupIdDelete'
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionGroupsPermissionGroupIdDeleteRequest($permission_group_id)
    {
        // verify the required parameter 'permission_group_id' is set
        if ($permission_group_id === null || (is_array($permission_group_id) && count($permission_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_group_id when calling apiV1PermissionGroupsPermissionGroupIdDelete'
            );
        }

        $resourcePath = '/api/v1/permission-groups/{permissionGroupId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($permission_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionGroupId' . '}',
                ObjectSerializer::toPathValue($permission_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdGet
     *
     * get one
     *
     * @param  int $permission_group_id permission_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionGroupsPermissionGroupIdGet($permission_group_id)
    {
        $this->apiV1PermissionGroupsPermissionGroupIdGetWithHttpInfo($permission_group_id);
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdGetWithHttpInfo
     *
     * get one
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionGroupsPermissionGroupIdGetWithHttpInfo($permission_group_id)
    {
        $request = $this->apiV1PermissionGroupsPermissionGroupIdGetRequest($permission_group_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdGetAsync
     *
     * get one
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdGetAsync($permission_group_id)
    {
        return $this->apiV1PermissionGroupsPermissionGroupIdGetAsyncWithHttpInfo($permission_group_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdGetAsyncWithHttpInfo
     *
     * get one
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdGetAsyncWithHttpInfo($permission_group_id)
    {
        $returnType = '';
        $request = $this->apiV1PermissionGroupsPermissionGroupIdGetRequest($permission_group_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionGroupsPermissionGroupIdGet'
     *
     * @param  int $permission_group_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionGroupsPermissionGroupIdGetRequest($permission_group_id)
    {
        // verify the required parameter 'permission_group_id' is set
        if ($permission_group_id === null || (is_array($permission_group_id) && count($permission_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_group_id when calling apiV1PermissionGroupsPermissionGroupIdGet'
            );
        }

        $resourcePath = '/api/v1/permission-groups/{permissionGroupId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($permission_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionGroupId' . '}',
                ObjectSerializer::toPathValue($permission_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdPut
     *
     * update
     *
     * @param  int $permission_group_id permission_group_id (required)
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $key key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionGroupsPermissionGroupIdPut($permission_group_id, $title_en, $title_bn, $key)
    {
        $this->apiV1PermissionGroupsPermissionGroupIdPutWithHttpInfo($permission_group_id, $title_en, $title_bn, $key);
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdPutWithHttpInfo
     *
     * update
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionGroupsPermissionGroupIdPutWithHttpInfo($permission_group_id, $title_en, $title_bn, $key)
    {
        $request = $this->apiV1PermissionGroupsPermissionGroupIdPutRequest($permission_group_id, $title_en, $title_bn, $key);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdPutAsync
     *
     * update
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdPutAsync($permission_group_id, $title_en, $title_bn, $key)
    {
        return $this->apiV1PermissionGroupsPermissionGroupIdPutAsyncWithHttpInfo($permission_group_id, $title_en, $title_bn, $key)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionGroupsPermissionGroupIdPutAsyncWithHttpInfo
     *
     * update
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPermissionGroupIdPutAsyncWithHttpInfo($permission_group_id, $title_en, $title_bn, $key)
    {
        $returnType = '';
        $request = $this->apiV1PermissionGroupsPermissionGroupIdPutRequest($permission_group_id, $title_en, $title_bn, $key);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionGroupsPermissionGroupIdPut'
     *
     * @param  int $permission_group_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionGroupsPermissionGroupIdPutRequest($permission_group_id, $title_en, $title_bn, $key)
    {
        // verify the required parameter 'permission_group_id' is set
        if ($permission_group_id === null || (is_array($permission_group_id) && count($permission_group_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_group_id when calling apiV1PermissionGroupsPermissionGroupIdPut'
            );
        }
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling apiV1PermissionGroupsPermissionGroupIdPut'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling apiV1PermissionGroupsPermissionGroupIdPut'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling apiV1PermissionGroupsPermissionGroupIdPut'
            );
        }

        $resourcePath = '/api/v1/permission-groups/{permissionGroupId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($key !== null) {
            if('form' === 'form' && is_array($key)) {
                foreach($key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key'] = $key;
            }
        }


        // path params
        if ($permission_group_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionGroupId' . '}',
                ObjectSerializer::toPathValue($permission_group_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PermissionGroupsPost
     *
     * create
     *
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $key key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1PermissionGroupsPost($title_en, $title_bn, $key)
    {
        $this->apiV1PermissionGroupsPostWithHttpInfo($title_en, $title_bn, $key);
    }

    /**
     * Operation apiV1PermissionGroupsPostWithHttpInfo
     *
     * create
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PermissionGroupsPostWithHttpInfo($title_en, $title_bn, $key)
    {
        $request = $this->apiV1PermissionGroupsPostRequest($title_en, $title_bn, $key);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PermissionGroupsPostAsync
     *
     * create
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPostAsync($title_en, $title_bn, $key)
    {
        return $this->apiV1PermissionGroupsPostAsyncWithHttpInfo($title_en, $title_bn, $key)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PermissionGroupsPostAsyncWithHttpInfo
     *
     * create
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PermissionGroupsPostAsyncWithHttpInfo($title_en, $title_bn, $key)
    {
        $returnType = '';
        $request = $this->apiV1PermissionGroupsPostRequest($title_en, $title_bn, $key);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PermissionGroupsPost'
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1PermissionGroupsPostRequest($title_en, $title_bn, $key)
    {
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling apiV1PermissionGroupsPost'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling apiV1PermissionGroupsPost'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling apiV1PermissionGroupsPost'
            );
        }

        $resourcePath = '/api/v1/permission-groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($key !== null) {
            if('form' === 'form' && is_array($key)) {
                foreach($key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key'] = $key;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getList0
     *
     * get list
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getList0()
    {
        $this->getList0WithHttpInfo();
    }

    /**
     * Operation getList0WithHttpInfo
     *
     * get list
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getList0WithHttpInfo()
    {
        $request = $this->getList0Request();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation getList0Async
     *
     * get list
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getList0Async()
    {
        return $this->getList0AsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getList0AsyncWithHttpInfo
     *
     * get list
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getList0AsyncWithHttpInfo()
    {
        $returnType = '';
        $request = $this->getList0Request();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getList0'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getList0Request()
    {

        $resourcePath = '/api/v1/permission-groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
