<?php
/**
 * RoleServicesApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * RoleServicesApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RoleServicesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1RolesGet
     *
     * get list
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1RolesGet()
    {
        $this->apiV1RolesGetWithHttpInfo();
    }

    /**
     * Operation apiV1RolesGetWithHttpInfo
     *
     * get list
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1RolesGetWithHttpInfo()
    {
        $request = $this->apiV1RolesGetRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1RolesGetAsync
     *
     * get list
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesGetAsync()
    {
        return $this->apiV1RolesGetAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1RolesGetAsyncWithHttpInfo
     *
     * get list
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesGetAsyncWithHttpInfo()
    {
        $returnType = '';
        $request = $this->apiV1RolesGetRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1RolesGet'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1RolesGetRequest()
    {

        $resourcePath = '/api/v1/roles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1RolesPost
     *
     * store
     *
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $key key (required)
     * @param  string $description description (optional)
     * @param  int $permission_group_id permission_group_id (optional)
     * @param  int $organization_id organization_id (optional)
     * @param  int $institute_id institute_id (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1RolesPost($title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        $this->apiV1RolesPostWithHttpInfo($title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id);
    }

    /**
     * Operation apiV1RolesPostWithHttpInfo
     *
     * store
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1RolesPostWithHttpInfo($title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        $request = $this->apiV1RolesPostRequest($title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1RolesPostAsync
     *
     * store
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesPostAsync($title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        return $this->apiV1RolesPostAsyncWithHttpInfo($title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1RolesPostAsyncWithHttpInfo
     *
     * store
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesPostAsyncWithHttpInfo($title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        $returnType = '';
        $request = $this->apiV1RolesPostRequest($title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1RolesPost'
     *
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1RolesPostRequest($title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling apiV1RolesPost'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling apiV1RolesPost'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling apiV1RolesPost'
            );
        }

        $resourcePath = '/api/v1/roles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($description !== null) {
            if('form' === 'form' && is_array($description)) {
                foreach($description as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['description'] = $description;
            }
        }
        // query params
        if ($key !== null) {
            if('form' === 'form' && is_array($key)) {
                foreach($key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key'] = $key;
            }
        }
        // query params
        if ($permission_group_id !== null) {
            if('form' === 'form' && is_array($permission_group_id)) {
                foreach($permission_group_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permission_group_id'] = $permission_group_id;
            }
        }
        // query params
        if ($organization_id !== null) {
            if('form' === 'form' && is_array($organization_id)) {
                foreach($organization_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['organization_id'] = $organization_id;
            }
        }
        // query params
        if ($institute_id !== null) {
            if('form' === 'form' && is_array($institute_id)) {
                foreach($institute_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['institute_id'] = $institute_id;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1RolesRoleIdAssignPermissionsPost
     *
     * assign-permission
     *
     * @param  int $role_id role_id (required)
     * @param  string $permissions_0 permissions_0 (optional)
     * @param  string $permissions_1 permissions_1 (optional)
     * @param  string $permissions_2 permissions_2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1RolesRoleIdAssignPermissionsPost($role_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $this->apiV1RolesRoleIdAssignPermissionsPostWithHttpInfo($role_id, $permissions_0, $permissions_1, $permissions_2);
    }

    /**
     * Operation apiV1RolesRoleIdAssignPermissionsPostWithHttpInfo
     *
     * assign-permission
     *
     * @param  int $role_id (required)
     * @param  string $permissions_0 (optional)
     * @param  string $permissions_1 (optional)
     * @param  string $permissions_2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1RolesRoleIdAssignPermissionsPostWithHttpInfo($role_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $request = $this->apiV1RolesRoleIdAssignPermissionsPostRequest($role_id, $permissions_0, $permissions_1, $permissions_2);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1RolesRoleIdAssignPermissionsPostAsync
     *
     * assign-permission
     *
     * @param  int $role_id (required)
     * @param  string $permissions_0 (optional)
     * @param  string $permissions_1 (optional)
     * @param  string $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdAssignPermissionsPostAsync($role_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        return $this->apiV1RolesRoleIdAssignPermissionsPostAsyncWithHttpInfo($role_id, $permissions_0, $permissions_1, $permissions_2)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1RolesRoleIdAssignPermissionsPostAsyncWithHttpInfo
     *
     * assign-permission
     *
     * @param  int $role_id (required)
     * @param  string $permissions_0 (optional)
     * @param  string $permissions_1 (optional)
     * @param  string $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdAssignPermissionsPostAsyncWithHttpInfo($role_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        $returnType = '';
        $request = $this->apiV1RolesRoleIdAssignPermissionsPostRequest($role_id, $permissions_0, $permissions_1, $permissions_2);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1RolesRoleIdAssignPermissionsPost'
     *
     * @param  int $role_id (required)
     * @param  string $permissions_0 (optional)
     * @param  string $permissions_1 (optional)
     * @param  string $permissions_2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1RolesRoleIdAssignPermissionsPostRequest($role_id, $permissions_0 = null, $permissions_1 = null, $permissions_2 = null)
    {
        // verify the required parameter 'role_id' is set
        if ($role_id === null || (is_array($role_id) && count($role_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $role_id when calling apiV1RolesRoleIdAssignPermissionsPost'
            );
        }

        $resourcePath = '/api/v1/roles/{roleId}/assign-permissions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($permissions_0 !== null) {
            if('form' === 'form' && is_array($permissions_0)) {
                foreach($permissions_0 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[0]'] = $permissions_0;
            }
        }
        // query params
        if ($permissions_1 !== null) {
            if('form' === 'form' && is_array($permissions_1)) {
                foreach($permissions_1 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[1]'] = $permissions_1;
            }
        }
        // query params
        if ($permissions_2 !== null) {
            if('form' === 'form' && is_array($permissions_2)) {
                foreach($permissions_2 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permissions[2]'] = $permissions_2;
            }
        }


        // path params
        if ($role_id !== null) {
            $resourcePath = str_replace(
                '{' . 'roleId' . '}',
                ObjectSerializer::toPathValue($role_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1RolesRoleIdDelete
     *
     * destroy
     *
     * @param  int $role_id role_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1RolesRoleIdDelete($role_id)
    {
        $this->apiV1RolesRoleIdDeleteWithHttpInfo($role_id);
    }

    /**
     * Operation apiV1RolesRoleIdDeleteWithHttpInfo
     *
     * destroy
     *
     * @param  int $role_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1RolesRoleIdDeleteWithHttpInfo($role_id)
    {
        $request = $this->apiV1RolesRoleIdDeleteRequest($role_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1RolesRoleIdDeleteAsync
     *
     * destroy
     *
     * @param  int $role_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdDeleteAsync($role_id)
    {
        return $this->apiV1RolesRoleIdDeleteAsyncWithHttpInfo($role_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1RolesRoleIdDeleteAsyncWithHttpInfo
     *
     * destroy
     *
     * @param  int $role_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdDeleteAsyncWithHttpInfo($role_id)
    {
        $returnType = '';
        $request = $this->apiV1RolesRoleIdDeleteRequest($role_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1RolesRoleIdDelete'
     *
     * @param  int $role_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1RolesRoleIdDeleteRequest($role_id)
    {
        // verify the required parameter 'role_id' is set
        if ($role_id === null || (is_array($role_id) && count($role_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $role_id when calling apiV1RolesRoleIdDelete'
            );
        }

        $resourcePath = '/api/v1/roles/{roleId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($role_id !== null) {
            $resourcePath = str_replace(
                '{' . 'roleId' . '}',
                ObjectSerializer::toPathValue($role_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1RolesRoleIdGet
     *
     * get one
     *
     * @param  int $role_id role_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1RolesRoleIdGet($role_id)
    {
        $this->apiV1RolesRoleIdGetWithHttpInfo($role_id);
    }

    /**
     * Operation apiV1RolesRoleIdGetWithHttpInfo
     *
     * get one
     *
     * @param  int $role_id (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1RolesRoleIdGetWithHttpInfo($role_id)
    {
        $request = $this->apiV1RolesRoleIdGetRequest($role_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1RolesRoleIdGetAsync
     *
     * get one
     *
     * @param  int $role_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdGetAsync($role_id)
    {
        return $this->apiV1RolesRoleIdGetAsyncWithHttpInfo($role_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1RolesRoleIdGetAsyncWithHttpInfo
     *
     * get one
     *
     * @param  int $role_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdGetAsyncWithHttpInfo($role_id)
    {
        $returnType = '';
        $request = $this->apiV1RolesRoleIdGetRequest($role_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1RolesRoleIdGet'
     *
     * @param  int $role_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1RolesRoleIdGetRequest($role_id)
    {
        // verify the required parameter 'role_id' is set
        if ($role_id === null || (is_array($role_id) && count($role_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $role_id when calling apiV1RolesRoleIdGet'
            );
        }

        $resourcePath = '/api/v1/roles/{roleId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($role_id !== null) {
            $resourcePath = str_replace(
                '{' . 'roleId' . '}',
                ObjectSerializer::toPathValue($role_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1RolesRoleIdPut
     *
     * store
     *
     * @param  int $role_id role_id (required)
     * @param  string $title_en title_en (required)
     * @param  string $title_bn title_bn (required)
     * @param  string $key key (required)
     * @param  string $description description (optional)
     * @param  int $permission_group_id permission_group_id (optional)
     * @param  int $organization_id organization_id (optional)
     * @param  int $institute_id institute_id (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1RolesRoleIdPut($role_id, $title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        $this->apiV1RolesRoleIdPutWithHttpInfo($role_id, $title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id);
    }

    /**
     * Operation apiV1RolesRoleIdPutWithHttpInfo
     *
     * store
     *
     * @param  int $role_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1RolesRoleIdPutWithHttpInfo($role_id, $title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        $request = $this->apiV1RolesRoleIdPutRequest($role_id, $title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1RolesRoleIdPutAsync
     *
     * store
     *
     * @param  int $role_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdPutAsync($role_id, $title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        return $this->apiV1RolesRoleIdPutAsyncWithHttpInfo($role_id, $title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1RolesRoleIdPutAsyncWithHttpInfo
     *
     * store
     *
     * @param  int $role_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1RolesRoleIdPutAsyncWithHttpInfo($role_id, $title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        $returnType = '';
        $request = $this->apiV1RolesRoleIdPutRequest($role_id, $title_en, $title_bn, $key, $description, $permission_group_id, $organization_id, $institute_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1RolesRoleIdPut'
     *
     * @param  int $role_id (required)
     * @param  string $title_en (required)
     * @param  string $title_bn (required)
     * @param  string $key (required)
     * @param  string $description (optional)
     * @param  int $permission_group_id (optional)
     * @param  int $organization_id (optional)
     * @param  int $institute_id (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function apiV1RolesRoleIdPutRequest($role_id, $title_en, $title_bn, $key, $description = null, $permission_group_id = null, $organization_id = null, $institute_id = null)
    {
        // verify the required parameter 'role_id' is set
        if ($role_id === null || (is_array($role_id) && count($role_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $role_id when calling apiV1RolesRoleIdPut'
            );
        }
        // verify the required parameter 'title_en' is set
        if ($title_en === null || (is_array($title_en) && count($title_en) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_en when calling apiV1RolesRoleIdPut'
            );
        }
        // verify the required parameter 'title_bn' is set
        if ($title_bn === null || (is_array($title_bn) && count($title_bn) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $title_bn when calling apiV1RolesRoleIdPut'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling apiV1RolesRoleIdPut'
            );
        }

        $resourcePath = '/api/v1/roles/{roleId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($title_en !== null) {
            if('form' === 'form' && is_array($title_en)) {
                foreach($title_en as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_en'] = $title_en;
            }
        }
        // query params
        if ($title_bn !== null) {
            if('form' === 'form' && is_array($title_bn)) {
                foreach($title_bn as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['title_bn'] = $title_bn;
            }
        }
        // query params
        if ($description !== null) {
            if('form' === 'form' && is_array($description)) {
                foreach($description as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['description'] = $description;
            }
        }
        // query params
        if ($key !== null) {
            if('form' === 'form' && is_array($key)) {
                foreach($key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key'] = $key;
            }
        }
        // query params
        if ($permission_group_id !== null) {
            if('form' === 'form' && is_array($permission_group_id)) {
                foreach($permission_group_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['permission_group_id'] = $permission_group_id;
            }
        }
        // query params
        if ($organization_id !== null) {
            if('form' === 'form' && is_array($organization_id)) {
                foreach($organization_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['organization_id'] = $organization_id;
            }
        }
        // query params
        if ($institute_id !== null) {
            if('form' === 'form' && is_array($institute_id)) {
                foreach($institute_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['institute_id'] = $institute_id;
            }
        }


        // path params
        if ($role_id !== null) {
            $resourcePath = str_replace(
                '{' . 'roleId' . '}',
                ObjectSerializer::toPathValue($role_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
