<?php
/**
 * DistrictApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DistrictApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DistrictApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1DistrictsDistrictIdGet
     *
     * get one.
     *
     */
    public function testApiV1DistrictsDistrictIdGet()
    {
    }

    /**
     * Test case for apiV1DistrictsGet
     *
     * get list.
     *
     */
    public function testApiV1DistrictsGet()
    {
    }

    /**
     * Test case for destroy1
     *
     * destroy.
     *
     */
    public function testDestroy1()
    {
    }

    /**
     * Test case for store2
     *
     * store.
     *
     */
    public function testStore2()
    {
    }

    /**
     * Test case for update3
     *
     * update.
     *
     */
    public function testUpdate3()
    {
    }
}
