<?php
/**
 * PermissionSubGroupServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PermissionSubGroupServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PermissionSubGroupServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1PermissionSubGroupsGet
     *
     * get list.
     *
     */
    public function testApiV1PermissionSubGroupsGet()
    {
    }

    /**
     * Test case for apiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPost
     *
     * assign-permission.
     *
     */
    public function testApiV1PermissionSubGroupsPermissionSubGroupIdAssignPermissionsPost()
    {
    }

    /**
     * Test case for apiV1PermissionSubGroupsPermissionSubGroupIdDelete
     *
     * delete.
     *
     */
    public function testApiV1PermissionSubGroupsPermissionSubGroupIdDelete()
    {
    }

    /**
     * Test case for apiV1PermissionSubGroupsPermissionSubGroupIdGet
     *
     * get one.
     *
     */
    public function testApiV1PermissionSubGroupsPermissionSubGroupIdGet()
    {
    }

    /**
     * Test case for apiV1PermissionSubGroupsPost
     *
     * create.
     *
     */
    public function testApiV1PermissionSubGroupsPost()
    {
    }

    /**
     * Test case for update4
     *
     * update.
     *
     */
    public function testUpdate4()
    {
    }
}
