<?php
/**
 * PermissionServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NISE_3_CORE_API
 *
 * It a core api service that manages Location Services,UserRoleManagement Services and Auth Services globally
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PermissionServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PermissionServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1PermissionsGet
     *
     * get list.
     *
     */
    public function testApiV1PermissionsGet()
    {
    }

    /**
     * Test case for apiV1PermissionsInstituteIdAssignPermissionsToInstitutePost
     *
     * assign-permissions-to-organization.
     *
     */
    public function testApiV1PermissionsInstituteIdAssignPermissionsToInstitutePost()
    {
    }

    /**
     * Test case for apiV1PermissionsPermissionIdPut
     *
     * update.
     *
     */
    public function testApiV1PermissionsPermissionIdPut()
    {
    }

    /**
     * Test case for apiV1PermissionsPost
     *
     * store.
     *
     */
    public function testApiV1PermissionsPost()
    {
    }

    /**
     * Test case for assignPermissionsToInstitute
     *
     * assign-permissions-to-institute.
     *
     */
    public function testAssignPermissionsToInstitute()
    {
    }

    /**
     * Test case for destroy6
     *
     * destroy.
     *
     */
    public function testDestroy6()
    {
    }

    /**
     * Test case for read1
     *
     * get one.
     *
     */
    public function testRead1()
    {
    }
}
